name: sign_language_app
description: A mobile app to learn sign language.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+5
  flutter_webrtc: ^0.13.1+hotfix.1
  http: ^1.3.0
  provider: ^6.1.1
  web_socket_channel: ^2.1.0
  shared_preferences: ^2.2.1
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    # Gesture images
    - lib/assets/gestures/
    # Alphabet images
    - lib/assets/alphabet/uk/
    - lib/assets/alphabet/en/
    # Test images
    - lib/assets/tests/
    # Default images
    - lib/assets/images/
    # Data files
    - lib/assets/data/
    # Default avatar
    - lib/assets/default_avatar.png


  uses-material-design: true